/*
 * Copyright 2017 Huub de Beer <huub@heerdebeer.org>
 *
 * This file is part of virtual_botanical_laboratory.
 *
 * virtual_botanical_laboratory is free software: you can redistribute it
 * and/or modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * virtual_botanical_laboratory is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
 * Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with virtual_botanical_laboratory.  If not, see
 * <http://www.gnu.org/licenses/>.
 * 
 */
export default `
    <head>
        <meta charset="utf-8">
        <title>Virtual Botanical Laboratory—__NAME__</title>
        <script src="__SOURCE_URL__"></script>
        <style>
            figcaption {
                font-style: italic;
            }

            figcaption .generator {
                font-size: smaller;
            }
        </style>
    <body>
        <figure>
            <figcaption>
                __DESCRIPTION__<br>
                <span class="generator">Generated by <a href="_https://github.com/htdebeer/virtual_botanical_laboratory">virtual_botanical_laboratory</a></span>
            </figcaption>
        </figure>
        <script>
            new virtual_botanical_laboratory.LabView(document.querySelector("figure"), __CONFIGURATION__);
        </script>`;
